### ISSUE TITLE
[Feature Req] Prompt template for chat LLM

### ISSUE THREAD

**Issue by Anthony-Hoo** [CSUSTers/csust-got#405]
希望能够在配置文件中定义chat指令的模版，从而同时支持多种不同的功能。
例如：

```
user: /ming op 原神 米哈游
bot： op只需要给原神充值就好了，米哈游要考虑的可就多了

user: /rayting op 原神 米哈游
bot: 原 孝 典
```

关于指令配置，需要在模版中新增一个定义字段，设计如下：

```yaml
prompt_template:
  -:
    name: "鸣式生成器"
    handle: "ming"
    system_prompt: "请根据输入文本，抽取其中的三个要素，按照顺序填充入以下句式：……"
    model: "qwen:14b"
  -:
    name: "成分鉴定器"
    handle: "rayting"
    system_prompt: "对于文本中的每句话，进行如下分类： 1.如果文本正在陈述观点，无论观点对错，你只需要回复我'典' 2.如果文本中存在偏袒某一方的行为，你只需要回复我'孝' ……"
    model: "qwen2:7b"
```

bot启动式解析一次配置文件 yaml，完成 telegram bot handle 的配置，收到相应指令时，按 prompt 和 model 的配置调用相关模型进行回复。
