### ISSUE TITLE
[Feature] AI/LLM functions summary

### ISSUE THREAD

**Issue by hugefiver** [CSUSTers/csust-got#550]
目前AI相关功能较为分散，提出该issue希望统一AI功能。

新的LLM相关功能使用同一的功能实现，通过不同的配置项的实现具有差异的具体功能。

配置项主要聚焦在以下三部分，通过灵活组合实现不同功能：
- 触发方式
  - 使用 `chat*` 命令主动触发
  - 通过regex匹配自动触发
- 模型配置
- system prompt

参考配置项如下：

```yaml
llm_models:
  gpt-xxx: &gpt
    base_url: "xxx"
    model: "gpt-xxx"
  qwen-xxx: &qwen
    base_url: "xxx"
    model: "qwen-xxx"

chats:
- name: 什么是bot
  context: 3 # reply msg上下文数量
  trigger:
  - chat_whatis # 使用 `/chat_whatis` 命令触发
  - regex: "^(什么是.*|.*是什么)[啊呢呀]?[??]*$" # 使用regex匹配触发
  - random: 0.1 # 随机触发
  model: *gpt
  placeholder: "⌛"
  stream: true
  system_promt: |
    THIS IS A SYSTEM PROMPT
  prompt: |
    THIS IS PROMPT
    {context}
    {input}
```
